<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Yuxuan Wang" />

<meta name="date" content="2021-11-23" />

<title>EDA</title>

<script src="site_libs/header-attrs-2.11/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/yeti.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>








<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="Proposal.html">Proposal</a>
</li>
<li>
  <a href="Exploratory-Analyses.html">Exploratory Analyses</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Recommendation Algorithm
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="SVD.html">SVD</a>
    </li>
    <li>
      <a href="tree-based-bootstraping.html">tree-based bootstraping</a>
    </li>
    <li>
      <a href="user-similarity.html">user-similarity based recommendation</a>
    </li>
  </ul>
</li>
<li>
  <a href="https://yw3608.shinyapps.io/Movie_Recommendation/">Shinyapps</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://github.com/ShaocongZ/Final_Project/">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">EDA</h1>
<h4 class="author">Yuxuan Wang</h4>
<h4 class="date">11/23/2021</h4>

</div>


<p><strong>Find popular movies and high-rating movies</strong></p>
<div id="import-dependencies" class="section level1">
<h1>Import dependencies</h1>
<pre class="r"><code>knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readr)
library(ggplot2)
library(kableExtra)</code></pre>
<div id="data-preparation" class="section level2">
<h2>Data preparation</h2>
<pre class="r"><code>data_path = &quot;./data/small/ratings.csv&quot;

rating_tidy = 
  read_csv(data_path, col_types = &quot;ccnc&quot;) %&gt;% 
    janitor::clean_names() %&gt;% 
    select(-timestamp) %&gt;% 
    mutate(rating = as.double(rating))  

high_rating = 
  rating_tidy %&gt;% 
  filter(rating == 5.0) 

movie_names = 
  read_csv(&quot;./data/small/movies.csv&quot;) %&gt;% 
  rename(movie_id = movieId)</code></pre>
</div>
</div>
<div id="test" class="section level1">
<h1>Test</h1>
<pre class="r"><code>high_rating_movienames = 
  merge(high_rating, movie_names) %&gt;% 
  group_by(title, genres,rating) %&gt;% 
  count(movie_id) %&gt;% 
  filter(n &gt;= 100) %&gt;% 
  select(n,title,genres,rating) %&gt;% 
  ungroup(title, genres,rating) %&gt;% 
  arrange(n) %&gt;% 
  knitr::kable() %&gt;% 
  kable_styling(bootstrap_options = c(&quot;striped&quot;))
high_rating_movienames </code></pre>
<table class="table table-striped" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
n
</th>
<th style="text-align:left;">
title
</th>
<th style="text-align:left;">
genres
</th>
<th style="text-align:right;">
rating
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
104
</td>
<td style="text-align:left;">
Star Wars: Episode IV - A New Hope (1977)
</td>
<td style="text-align:left;">
Action|Adventure|Sci-Fi
</td>
<td style="text-align:right;">
5
</td>
</tr>
<tr>
<td style="text-align:right;">
109
</td>
<td style="text-align:left;">
Matrix, The (1999)
</td>
<td style="text-align:left;">
Action|Sci-Fi|Thriller
</td>
<td style="text-align:right;">
5
</td>
</tr>
<tr>
<td style="text-align:right;">
116
</td>
<td style="text-align:left;">
Forrest Gump (1994)
</td>
<td style="text-align:left;">
Comedy|Drama|Romance|War
</td>
<td style="text-align:right;">
5
</td>
</tr>
<tr>
<td style="text-align:right;">
123
</td>
<td style="text-align:left;">
Pulp Fiction (1994)
</td>
<td style="text-align:left;">
Comedy|Crime|Drama|Thriller
</td>
<td style="text-align:right;">
5
</td>
</tr>
<tr>
<td style="text-align:right;">
153
</td>
<td style="text-align:left;">
Shawshank Redemption, The (1994)
</td>
<td style="text-align:left;">
Crime|Drama
</td>
<td style="text-align:right;">
5
</td>
</tr>
</tbody>
</table>
<p><strong>Find popular movies and high-rating movies</strong> : In order to find the top 5 popular movies with highest rating, we filtered movies with rating less than 5, and count the 5 most rated movies. The Shawshank Redemption (1994) is the most popular movie, which has 153 times user rating. No.2 Pulp Fiction (1994), has 123 times user rating. 116 times user rating, Forrest Gump (1994) wins the 3rd popular place. The Matrix (1999) has 109 times user rating,and is the fourth place among the top 5 popular movies. No. 5 is Star Wars: Episode IV - A New Hope (1977), and it has 104 times user rating. We also find out that among those 5 most rated movies and highest rating movies, genres with tag drama appears the most(3 times, appear in Forrest Gump (1994), Pulp Fiction (1994),The Shawshank Redemption (1994)). We also find out one interesting fact is that among the 5 most popular movies and 5 highest rating movies, 3 movies are released in 1994; 4 movies are released in the 90s.</p>
<p><strong>Boxplot regarding ratings and genres</strong></p>
<pre class="r"><code>movie_names = 
  read_csv(&quot;./data/small/movies.csv&quot;) %&gt;% 
  rename(movie_id = movieId)

filter_ratingscore = 
  rating_tidy  

boxplot_df = 
  merge(filter_ratingscore, movie_names) %&gt;%
  head(400) %&gt;%
 ggplot(aes(x = genres, y = rating),color = genres) + geom_boxplot()
boxplot_df </code></pre>
<p><img src="EDA_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p><strong>Boxplot regarding: ratings and years</strong></p>
<pre class="r"><code>movie_names = 
  read_csv(&quot;./data/small/movies.csv&quot;) %&gt;% 
  rename(movie_id = movieId) %&gt;% 
  separate(
  title, c(&quot;name&quot;, &quot;year&quot;), sep=&quot;\\s+(?=\\S*$)&quot;) 
boxplot_df2 = 
  merge(filter_ratingscore, movie_names) %&gt;%
  head(500) %&gt;%
  ggplot(aes(x = year, y = rating),color = year) + geom_boxplot()+
  viridis::scale_fill_viridis(discrete = TRUE)
boxplot_df2 </code></pre>
<p><img src="EDA_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p><strong>Find the average rating of each categories in different year</strong></p>
<pre class="r"><code>movie_names = 
  read_csv(&quot;./data/small/movies.csv&quot;) %&gt;% 
  rename(movie_id = movieId) %&gt;% 
  separate(
  title, c(&quot;name&quot;, &quot;year&quot;), sep=&quot;\\s+(?=\\S*$)&quot;) 
ave_rating = 
  merge(filter_ratingscore, movie_names) %&gt;% 
  group_by(year,genres) %&gt;%
  summarize(mu_rating = mean(rating)) %&gt;% 
  head(10) %&gt;% 
  knitr::kable() %&gt;%
kable_styling(bootstrap_options = c(&quot;striped&quot;))
ave_rating</code></pre>
<table class="table table-striped" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
year
</th>
<th style="text-align:left;">
genres
</th>
<th style="text-align:right;">
mu_rating
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
<ol start="1902" style="list-style-type: decimal">
<li></td>
<td style="text-align:left;">
Action|Adventure|Fantasy|Sci-Fi
</td>
<td style="text-align:right;">
3.50
</td>
</tr>
<tr>
<td style="text-align:left;">
<ol start="1903" style="list-style-type: decimal">
<li></td>
<td style="text-align:left;">
Crime|Western
</td>
<td style="text-align:right;">
2.50
</td>
</tr>
<tr>
<td style="text-align:left;">
<ol start="1908" style="list-style-type: decimal">
<li></td>
<td style="text-align:left;">
Animation|Comedy|Sci-Fi
</td>
<td style="text-align:right;">
4.00
</td>
</tr>
<tr>
<td style="text-align:left;">
<ol start="1915" style="list-style-type: decimal">
<li></td>
<td style="text-align:left;">
Drama|War
</td>
<td style="text-align:right;">
2.00
</td>
</tr>
<tr>
<td style="text-align:left;">
<ol start="1916" style="list-style-type: decimal">
<li></td>
<td style="text-align:left;">
Action|Adventure|Sci-Fi
</td>
<td style="text-align:right;">
3.75
</td>
</tr>
<tr>
<td style="text-align:left;">
<ol start="1916" style="list-style-type: decimal">
<li></td>
<td style="text-align:left;">
Comedy
</td>
<td style="text-align:right;">
3.50
</td>
</tr>
<tr>
<td style="text-align:left;">
<ol start="1916" style="list-style-type: decimal">
<li></td>
<td style="text-align:left;">
Drama
</td>
<td style="text-align:right;">
3.50
</td>
</tr>
<tr>
<td style="text-align:left;">
<ol start="1916" style="list-style-type: decimal">
<li></td>
<td style="text-align:left;">
Fantasy|Romance
</td>
<td style="text-align:right;">
3.50
</td>
</tr>
<tr>
<td style="text-align:left;">
<ol start="1917" style="list-style-type: decimal">
<li></td>
<td style="text-align:left;">
Comedy
</td>
<td style="text-align:right;">
4.50
</td>
</tr>
<tr>
<td style="text-align:left;">
<ol start="1919" style="list-style-type: decimal">
<li></td>
<td style="text-align:left;">
Comedy|Drama
</td>
<td style="text-align:right;">
2.00
</td>
</tr>
</tbody>
</table></li>
</ol></li>
</ol></li>
</ol></li>
</ol></li>
</ol></li>
</ol></li>
</ol></li>
</ol></li>
</ol></li>
</ol>
<p><strong>Test the average ratings of the users, to investigate whether the rating criteria are different.(ANOVA)</strong></p>
<p>𝐻0:𝜇1=𝜇2=…=𝜇600</p>
<p>𝐻1:at least two of the mean ratings of the user from the 600 users are different</p>
<pre class="r"><code>filter_ratingscore = rating_tidy 
res = lm(rating ~ factor(user_id), data = filter_ratingscore)   
anova(res) %&gt;% 
  kable() %&gt;% 
  kable_styling(bootstrap_options = c(&quot;striped&quot;))</code></pre>
<table class="table table-striped" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Df
</th>
<th style="text-align:right;">
Sum Sq
</th>
<th style="text-align:right;">
Mean Sq
</th>
<th style="text-align:right;">
F value
</th>
<th style="text-align:right;">
Pr(&gt;F)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
factor(user_id)
</td>
<td style="text-align:right;">
609
</td>
<td style="text-align:right;">
21493.48
</td>
<td style="text-align:right;">
35.2930699
</td>
<td style="text-align:right;">
40.15042
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
Residuals
</td>
<td style="text-align:right;">
100226
</td>
<td style="text-align:right;">
88100.78
</td>
<td style="text-align:right;">
0.8790212
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
</tr>
</tbody>
</table>
<p>At 0.05 significance level, we reject the null hypothesis and conclude that at least two of the mean ratings of the user from the 600 users are different.</p>
<pre class="r"><code>kruskal.test(rating ~ user_id, data = filter_ratingscore) </code></pre>
<pre><code>## 
##  Kruskal-Wallis rank sum test
## 
## data:  rating by user_id
## Kruskal-Wallis chi-squared = 20677, df = 609, p-value &lt; 2.2e-16</code></pre>
<p>At 0.05 significance level, we reject the null hypothesis and conclude that at least two of the mean ratings of the user from the 600 users are different.</p>
<p><strong>linear regression graph to show a specific user’s rating on genre</strong> Linearity: The relationship between X and the mean of Y is linear. Homoscedasticity: The variance of residual is the same for any value of X. Independence: Observations are independent of each other. Normality: For any fixed value of X, Y is normally distributed. To check whether the dependent(y)variable follows a normal distribution, use the hist() function.</p>
<pre class="r"><code>ave_rating = 
  merge(filter_ratingscore, movie_names)
hist(ave_rating$rating)</code></pre>
<p><img src="EDA_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
