---
title: "**Movie Recommender**"
output: 
  html_document:
    code_folding: hide
---
<style type="text/css">

h1.title {
  font-size: 38px;
  color: Black;
  text-align: center;
}

h4.author { /* Header 4 - and the author and data headers use this too  */
    font-size: 18px;
  font-family: "Times New Roman", Times, serif;
  color: DarkRed;
  text-align: center;
}

</style>

<center>
<font size = "5">

A demo movie recommendation system

</font>
</center>

<iframe width="560" height="315" src="https://www.youtube.com/watch?v=6vIq99VgxkE" frameborder="0" allowfullscreen></iframe>

 
$\quad$
$\quad$
 
# About the project

The progress of computer and Internet technology has promoted the development of society. In terms of entertainment, the vibrant film industry is now facing another revolution with the support of the Internet and big data. How to accurately recommend information to users that matches their preferences has become an important application and a major challenge in the field of data science. In this way, many websites have established complex, reliable and highly accurate film preference recommendation algorithms or systems. These algorithms or systems are great inventions, which can effectively meet the users' need of watching movies and greatly reduce the time required for users to search movies. In this context, we want to try to make a demo movie recommendation system based on [movielens](https://grouplens.org/datasets/movielens/latest/) data set, and try to apply the recommendation system used in daily life to our own website.

$\quad$
$\quad$

# Website Overview

This website is designed to construct a demo movie recommendation based on the [movielens](https://grouplens.org/datasets/movielens/latest/) dataset. The dataset describes 5-star rating and free-text tagging activity from the movie recommendation service. When exploring the website, you will find the [Exploratory Analyses](EDA.html), Recommendation Algorithm and Shinyapp tabs.

$\quad$

In the [Exploratory Analyses](EDA.html) tab, you will find:

$\bullet$ Brief analyses of the dataset

$\bullet$ Deeper analyses of the dataset, through statistical tests and visualization

$\quad$

In the Recommendation Algorithm tab, you will find the concepts, working process and results of:

$\bullet$ [Tree-based bootstrapping](tree-based-bootstraping.html)

$\bullet$ [Similarity-based recommendation](user_similarity.html)

$\bullet$ [SVD-based recommendation](SVD.html)

$\bullet$ [Tag-based recommendation](tag_system_recommendation.html)

$\quad$

The [shinyapp](https://hzhong.shinyapps.io/movierecommender/) tab will lead you have an amazing experience of how the movie recommendation system works.

You can also see our  proposal [here](Proposal.html).

$\quad$
$\quad$

# Additional Information

$\bullet$ Watch our project [Youtube video](https://www.youtube.com/watch?v=6vIq99VgxkE) and get a brief understanding of this amazing project.

$\bullet$ You can read our final project report here to get a comprehensive understanding of how this wonderful project was constructed from start to finish.

$\quad$
$\quad$

### Collaborators:

$\bullet$ Haoling Zhong

$\bullet$ Shaocong Zhang

$\bullet$ Yuxuan Wang

$\bullet$ Boqian Zhang

