---
title: "tag_system_recommendation"
author: "Shaocong Zhang"
date: "11/22/2021"
output: html_document
---

Data wrangling on tags

```{r}
library(tidyverse)
```

```{r}
# data import
movies = read_csv("../data/small/movies.csv")
ratings = read_csv("../data/small/ratings.csv")
tags = read_csv("../data/small/tags.csv")
```

```{r}
# data wrangling
tags.user = 
  tags %>%
  janitor::clean_names() %>%
  mutate(
    tag = strsplit(tag, " ")
  ) %>%
  select(user_id, movie_id, tag) %>%
  nest(data = tag) 
  

tags.movie = 
  tags %>%
  janitor::clean_names() %>%
  mutate(
    tag = strsplit(tag, " ")
  ) %>%
  select(user_id, movie_id, tag) %>%
  nest(data = c(user_id,tag))

tags.full = 
  tags %>%
  janitor::clean_names() %>%
  mutate(
    tag = strsplit(tag, " ")
  ) %>%
  unnest()
```


```{r}
# Set up interest function
interest.fc = function(u, i) {
test.dat = 
  tags.full %>%
  filter(user_id == u,
         movie_id == i)

test.moive = 
  tags.full %>%
  filter(movie_id == i)

interest = c()
value = c()
n_b_u = c(rep(0, nrow(test.dat)))
n_i_u = length(unique(test.moive$user_id))
for (b in 1:nrow(test.dat)) {
  tag = as.character(test.dat[b,3])
  n_ub = sum(test.dat$tag == tag)
  n_bi = sum(test.moive$tag == tag)
  interest[b] = n_ub*n_bi
  for (j in unique(tags.full$user_id)) {
    dat.u = 
      tags.full %>%
      filter(user_id == j)
    tag = as.character(test.dat[b,3])
    if (sum(dat.u$tag == tag) != 0) {
      n_b_u[b] = n_b_u[b] + 1
    } else {
      n_b_u[b] = n_b_u[b]
    }
  }
  value[b] = interest[b] / (log(1 + n_b_u[b]) * log(1 + n_i_u))
}
return(interest = sum(value))
}
```



```{r}
# calculate TF-IDF
test = 
  tags.user %>%
  select(-data)

interest = c()

for (j in 1:nrow(test)) {
  u = as.numeric(test[j,1])
  i = as.numeric(test[j,2])
  interest[j] = interest.fc(u, i)
}
  
interest

test = 
  test %>%
  mutate(
    interest = interest
  )
```


```{r}
test.dat = 
  tags.full %>%
  filter(user_id == 2,
         movie_id == 60756)

test.moive = 
  tags.full %>%
  filter(movie_id == 60756)

interest = c()
value = c()
n_b_u = c(rep(0, nrow(test.dat)))
n_i_u = length(unique(test.moive$user_id))
for (b in 1:nrow(test.dat)) {
  tag = as.character(test.dat[b,3])
  n_ub = sum(test.dat$tag == tag)
  n_bi = sum(test.moive$tag == tag)
  interest[b] = n_ub*n_bi
  for (j in unique(tags.full$user_id)) {
    dat.u = 
      tags.full %>%
      filter(user_id == j)
    tag = as.character(test.dat[b,3])
    if (sum(dat.u$tag == tag) != 0) {
      n_b_u[b] = n_b_u[b] + 1
    } else {
      n_b_u[b] = n_b_u[b]
    }
  }
  value[b] = interest[b] / (log(1 + n_b_u[b]) * log(1 + n_i_u))
}



return(interest = sum(value))

```




